use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum TokenKind {
    // keywords
    Def,
    Class,
    Async,
    Return,
    If,
    Else,
    Elif,
    While,
    For,
    In,
    Break,
    Continue,
    True,
    False,
    Nil,
    Let,
    Use,
    As,
    Pub,
    Trait,
    Includes,
    Extends,
    Throw,
    Throws,
    Match,
    Catch,
    Resolve,
    Detached,
    Scope,
    // structure
    Indent,
    Dedent,
    Newline,
    EOF,
    // punctuation / operators
    LParen,
    RParen,
    Comma,
    Colon,
    Arrow,
    Dot,
    Equals,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    StarStar,
    EqualEqual,
    BangEqual,
    Less,
    Greater,
    LessEqual,
    GreaterEqual,
    And,
    Or,
    Not,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Question,
    Bang,
    FatArrow,
    // literals / idents
    Int(i64),
    Float(f64),
    Str(String),
    Ident(String),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Token {
    pub kind: TokenKind,
    pub line: usize,
    pub col: usize,
    /// Byte offset of the first character of this token in the source.
    pub start: usize,
    /// Byte offset one past the last character of this token in the source.
    pub end: usize,
}
