use std::fmt;

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum TokenKind {
    // keywords
    Def,
    Class,
    Async,
    Blocking,
    Return,
    If,
    Else,
    Elif,
    While,
    For,
    In,
    Break,
    Continue,
    True,
    False,
    Nil,
    Let,
    Use,
    As,
    Pub,
    Trait,
    Enum,
    Includes,
    Extends,
    Throw,
    Throws,
    Match,
    Catch,
    Resolve,
    Detached,
    Const,
    // structure
    Indent,
    Dedent,
    Newline,
    EOF,
    // punctuation / operators
    LParen,
    RParen,
    Comma,
    Colon,
    Arrow,
    Dot,
    DotDot,
    DotDotEq,
    Equals,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    StarStar,
    EqualEqual,
    BangEqual,
    Less,
    Greater,
    LessEqual,
    GreaterEqual,
    And,
    Or,
    Not,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Question,
    Bang,
    FatArrow,
    // literals / idents
    Int(i64),
    Float(f64),
    Str(String),
    Ident(String),
    // String interpolation tokens: "hello {name} world" becomes
    // StringStart("hello "), ...expr tokens..., StringMid(" world"), StringEnd("")
    // or StringStart("hello "), ...expr..., StringEnd(" world")
    StringStart(String),
    StringMid(String),
    StringEnd(String),
}

impl fmt::Display for TokenKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Def => write!(f, "def"),
            Self::Class => write!(f, "class"),
            Self::Async => write!(f, "async"),
            Self::Blocking => write!(f, "blocking"),
            Self::Return => write!(f, "return"),
            Self::If => write!(f, "if"),
            Self::Else => write!(f, "else"),
            Self::Elif => write!(f, "elif"),
            Self::While => write!(f, "while"),
            Self::For => write!(f, "for"),
            Self::In => write!(f, "in"),
            Self::Break => write!(f, "break"),
            Self::Continue => write!(f, "continue"),
            Self::True => write!(f, "true"),
            Self::False => write!(f, "false"),
            Self::Nil => write!(f, "nil"),
            Self::Let => write!(f, "let"),
            Self::Use => write!(f, "use"),
            Self::As => write!(f, "as"),
            Self::Pub => write!(f, "pub"),
            Self::Trait => write!(f, "trait"),
            Self::Enum => write!(f, "enum"),
            Self::Includes => write!(f, "includes"),
            Self::Extends => write!(f, "extends"),
            Self::Throw => write!(f, "throw"),
            Self::Throws => write!(f, "throws"),
            Self::Match => write!(f, "match"),
            Self::Catch => write!(f, "catch"),
            Self::Resolve => write!(f, "resolve"),
            Self::Detached => write!(f, "detached"),
            Self::Const => write!(f, "const"),
            Self::Indent => write!(f, "indent"),
            Self::Dedent => write!(f, "dedent"),
            Self::Newline => write!(f, "newline"),
            Self::EOF => write!(f, "end of file"),
            Self::LParen => write!(f, "("),
            Self::RParen => write!(f, ")"),
            Self::Comma => write!(f, ","),
            Self::Colon => write!(f, ":"),
            Self::Arrow => write!(f, "->"),
            Self::Dot => write!(f, "."),
            Self::DotDot => write!(f, ".."),
            Self::DotDotEq => write!(f, "..="),
            Self::Equals => write!(f, "="),
            Self::Plus => write!(f, "+"),
            Self::Minus => write!(f, "-"),
            Self::Star => write!(f, "*"),
            Self::Slash => write!(f, "/"),
            Self::Percent => write!(f, "%"),
            Self::StarStar => write!(f, "**"),
            Self::EqualEqual => write!(f, "=="),
            Self::BangEqual => write!(f, "!="),
            Self::Less => write!(f, "<"),
            Self::Greater => write!(f, ">"),
            Self::LessEqual => write!(f, "<="),
            Self::GreaterEqual => write!(f, ">="),
            Self::And => write!(f, "and"),
            Self::Or => write!(f, "or"),
            Self::Not => write!(f, "not"),
            Self::LBracket => write!(f, "["),
            Self::RBracket => write!(f, "]"),
            Self::LBrace => write!(f, "{{"),
            Self::RBrace => write!(f, "}}"),
            Self::Question => write!(f, "?"),
            Self::Bang => write!(f, "!"),
            Self::FatArrow => write!(f, "=>"),
            Self::Int(v) => write!(f, "{}", v),
            Self::Float(v) => write!(f, "{}", v),
            Self::Str(s) => write!(f, "\"{}\"", s),
            Self::Ident(s) => write!(f, "{}", s),
            Self::StringStart(s) => write!(f, "\"{}{{", s),
            Self::StringMid(s) => write!(f, "}}{}{{", s),
            Self::StringEnd(s) => write!(f, "}}{}", s),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Token {
    pub kind: TokenKind,
    pub line: usize,
    pub col: usize,
    /// Byte offset of the first character of this token in the source.
    pub start: usize,
    /// Byte offset one past the last character of this token in the source.
    pub end: usize,
}
