use cranelift_jit::JITBuilder;

pub mod alloc;
pub mod channel;
pub mod crypto;
pub mod error;
pub mod fs;
pub mod gc;
pub mod introspection;
pub mod io;
pub mod list;
pub mod map;
pub mod mutex;
pub mod numeric;
pub mod print;
pub mod process;
pub mod runtime_eval;
pub mod string;
pub mod sys;
pub mod task;

// Re-export everything so external code can use `crate::runtime::*` or
// `crate::runtime::some_fn` without knowing the internal module layout.

pub use alloc::{aster_alloc, aster_class_alloc, aster_class_alloc_typed, aster_closure_alloc};

pub use string::{
    aster_bool_to_string, aster_float_to_string, aster_int_to_string, aster_string_char_len,
    aster_string_compare, aster_string_concat, aster_string_contains, aster_string_ends_with,
    aster_string_eq, aster_string_len, aster_string_new, aster_string_replace, aster_string_slice,
    aster_string_split, aster_string_starts_with, aster_string_to_lower, aster_string_to_upper,
    aster_string_trim,
};

pub use list::{
    aster_list_contains, aster_list_get, aster_list_insert, aster_list_len, aster_list_new,
    aster_list_pop, aster_list_push, aster_list_random, aster_list_remove, aster_list_set,
    aster_list_to_string,
};

pub use map::{aster_map_get, aster_map_has_key, aster_map_new, aster_map_set};

pub use gc::{aster_gc_collect, aster_gc_pop_roots, aster_gc_push_roots};
pub(crate) use gc::{shadow_stack_get, shadow_stack_set};

pub use error::{
    aster_async_scope_enter, aster_async_scope_exit, aster_error_check, aster_error_get_tag,
    aster_error_get_value, aster_error_set, aster_error_set_typed, aster_panic, aster_safepoint,
};
pub(crate) use error::{error_flag_get, error_flag_set};

pub use task::{
    aster_task_block_on, aster_task_cancel, aster_task_from_f64, aster_task_from_i8,
    aster_task_from_i64, aster_task_is_ready, aster_task_resolve_all_i64, aster_task_resolve_f64,
    aster_task_resolve_first_i64, aster_task_resolve_i8, aster_task_resolve_i64, aster_task_spawn,
    aster_task_wait_cancel,
};

pub use mutex::{aster_mutex_get_value, aster_mutex_lock, aster_mutex_new, aster_mutex_unlock};

pub use channel::{
    aster_channel_close, aster_channel_new, aster_channel_receive, aster_channel_send,
    aster_channel_try_receive, aster_channel_try_send, aster_channel_wait_receive,
    aster_channel_wait_send,
};

pub use io::{
    aster_blocking_submit, aster_file_append, aster_file_read, aster_file_write,
    aster_io_wait_read, aster_io_wait_write,
};

pub use print::{aster_say_bool, aster_say_float, aster_say_int, aster_say_str};

pub use introspection::{
    aster_introspect_ancestors, aster_introspect_children, aster_introspect_class_name,
    aster_introspect_fields, aster_introspect_is_a, aster_introspect_methods,
    aster_introspect_responds_to,
};

pub use sys::{aster_sys_args, aster_sys_env_get, aster_sys_env_set, aster_sys_exit};

pub use fs::{
    aster_fs_append_file, aster_fs_copy, aster_fs_exists, aster_fs_is_dir, aster_fs_list_dir,
    aster_fs_mkdir, aster_fs_read_file, aster_fs_remove, aster_fs_rename, aster_fs_write_file,
};

pub use process::aster_process_run;

pub use crypto::aster_crypto_sha256;

pub use runtime_eval::{aster_runtime_eval_with_ctx, aster_runtime_jit_eval};

pub use numeric::{
    aster_float_abs, aster_float_ceil, aster_float_clamp, aster_float_floor, aster_float_max,
    aster_float_min, aster_float_round, aster_int_abs, aster_int_add, aster_int_clamp,
    aster_int_is_even, aster_int_is_odd, aster_int_max, aster_int_min, aster_int_mul,
    aster_int_sub, aster_pow_float, aster_pow_int, aster_random_bool, aster_random_float,
    aster_random_int, aster_range_check, aster_range_new,
};

/// Register all runtime builtins with a JIT builder.
/// Symbol table is generated by the `runtime_functions!` macro in `runtime_sigs`.
pub fn register_runtime_builtins(builder: &mut JITBuilder) {
    builder.symbols(crate::runtime_sigs::runtime_builtin_symbols());
}
